
-- =============================================================
-- FIX: NOTIFICATIONS SCHEMA AND TRIGGER ERRORS
-- Resolves "record 'new' has no field 'phone_number'" in appointments creation
-- Also fixes several phone vs phone_number column mismatches in CRM tables.
-- =============================================================

-- 1. Add missing columns to notifications
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS tutor_id UUID REFERENCES public.tutors(id) ON DELETE SET NULL;

-- 2. Correct handle_manual_message_pause (for WhatsApp manual responses)
CREATE OR REPLACE FUNCTION public.handle_manual_message_pause()
RETURNS TRIGGER AS $$
BEGIN
    -- If the message is OUTBOUND and NOT generated by AI, it's a human (Claudia)
    IF (NEW.direction = 'outbound' AND (NEW.ai_generated IS NULL OR NEW.ai_generated = false)) THEN
        -- Pause the tutor
        UPDATE public.tutors 
        SET requires_human = true 
        WHERE clinic_id = NEW.clinic_id AND phone_number = NEW.phone_number;

        -- Pause the prospect (CRM) - FIX: Column is 'phone' in crm_prospects
        UPDATE public.crm_prospects 
        SET requires_human = true 
        WHERE clinic_id = NEW.clinic_id AND phone = NEW.phone_number;
        
        RAISE NOTICE 'AI Paused for patient % due to manual message', NEW.phone_number;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Update handle_appointment_notifications to include metadata
CREATE OR REPLACE FUNCTION public.handle_appointment_notifications()
RETURNS TRIGGER AS $$
DECLARE
    prefs RECORD;
    notif_title TEXT;
    notif_msg TEXT;
    notif_type TEXT;
    should_notify BOOLEAN := false;
BEGIN
    -- Fetch the clinic notification preferences
    SELECT * INTO prefs FROM public.notification_preferences WHERE clinic_id = NEW.clinic_id LIMIT 1;
    
    -- Case 1: New Appointment
    IF TG_OP = 'INSERT' THEN
        notif_type := 'new_appointment';
        notif_title := 'Nueva Cita';
        notif_msg := 'Se ha agendado una cita para ' || NEW.patient_name || ' (' || COALESCE(NEW.service, 'consulta') || ').';
        
        IF prefs IS NULL OR COALESCE(prefs.new_appointment, true) THEN
            should_notify := true;
        END IF;

    -- Case 2: Status Update
    ELSIF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
        IF NEW.status = 'confirmed' THEN
            notif_type := 'confirmed_appointment';
            notif_title := 'Cita Confirmada';
            notif_msg := 'La cita de ' || NEW.patient_name || ' ha sido confirmada.';
            IF prefs IS NULL OR COALESCE(prefs.confirmed, true) THEN
                should_notify := true;
            END IF;
        ELSIF NEW.status = 'completed' THEN
            notif_type := 'completed_appointment';
            notif_title := 'Cita Finalizada';
            notif_msg := 'La cita de ' || NEW.patient_name || ' ha finalizado.';
            IF prefs IS NULL OR COALESCE(prefs.completed, true) THEN
                should_notify := true;
            END IF;
        ELSIF NEW.status = 'cancelled' THEN
            notif_type := 'cancelled_appointment';
            notif_title := 'Cita Cancelada';
            notif_msg := 'La cita de ' || NEW.patient_name || ' ha sido cancelada.';
            IF prefs IS NULL OR COALESCE(prefs.cancelled, true) THEN
                should_notify := true;
            END IF;
        END IF;
    END IF;

    -- Insert notification with phone_number and tutor_id
    IF should_notify THEN
        INSERT INTO public.notifications (
            clinic_id, 
            type, 
            title, 
            message, 
            link, 
            phone_number, 
            tutor_id
        )
        VALUES (
            NEW.clinic_id, 
            notif_type, 
            notif_title, 
            notif_msg, 
            '/appointments', 
            NEW.phone_number, 
            NEW.tutor_id
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Correct handle_surgery_handoff_pause (on notifications)
CREATE OR REPLACE FUNCTION public.handle_surgery_handoff_pause()
RETURNS TRIGGER AS $$
BEGIN
    -- If a notification mentions surgery or handoff for a specific patient
    IF (NEW.title ILIKE '%Cirugía%' OR NEW.title ILIKE '%Handoff%') AND NEW.phone_number IS NOT NULL THEN
        UPDATE public.tutors 
        SET requires_human = true 
        WHERE clinic_id = NEW.clinic_id AND phone_number = NEW.phone_number;

        -- FIX: Column is 'phone' in crm_prospects
        UPDATE public.crm_prospects 
        SET requires_human = true 
        WHERE clinic_id = NEW.clinic_id AND phone = NEW.phone_number;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
