-- 1. Function to auto-pause AI when a human sends a message
CREATE OR REPLACE FUNCTION public.handle_manual_message_pause()
RETURNS TRIGGER AS $$
BEGIN
    -- If the message is OUTBOUND and NOT generated by AI, it's a human (Claudia)
    IF (NEW.direction = 'outbound' AND (NEW.ai_generated IS NULL OR NEW.ai_generated = false)) THEN
        -- Pause the tutor
        UPDATE public.tutors 
        SET requires_human = true 
        WHERE clinic_id = NEW.clinic_id AND phone_number = NEW.phone_number;

        -- Pause the prospect (CRM)
        UPDATE public.crm_prospects 
        SET requires_human = true 
        WHERE clinic_id = NEW.clinic_id AND phone_number = NEW.phone_number;
        
        RAISE NOTICE 'AI Paused for patient % due to manual message', NEW.phone_number;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. Trigger for manual message pause
DROP TRIGGER IF EXISTS on_manual_message_pause ON public.messages;
CREATE TRIGGER on_manual_message_pause
AFTER INSERT ON public.messages
FOR EACH ROW
EXECUTE FUNCTION public.handle_manual_message_pause();

-- 3. Ensure surgery intent NOTIFICATIONS also set requires_human (Optional but recommended)
CREATE OR REPLACE FUNCTION public.handle_surgery_handoff_pause()
RETURNS TRIGGER AS $$
BEGIN
    -- If a notification mentions surgery or handoff for a specific patient
    IF (NEW.title ILIKE '%Cirugía%' OR NEW.title ILIKE '%Handoff%') AND NEW.phone_number IS NOT NULL THEN
        UPDATE public.tutors SET requires_human = true WHERE clinic_id = NEW.clinic_id AND phone_number = NEW.phone_number;
        UPDATE public.crm_prospects SET requires_human = true WHERE clinic_id = NEW.clinic_id AND phone_number = NEW.phone_number;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_surgery_notification_pause ON public.notifications;
CREATE TRIGGER on_surgery_notification_pause
AFTER INSERT ON public.notifications
FOR EACH ROW
EXECUTE FUNCTION public.handle_surgery_handoff_pause();
